# Generated by Django 3.2.3 on 2021-05-26 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('date', models.DateTimeField(verbose_name='Дата проведения')),
                ('location', models.CharField(max_length=255, verbose_name='Место проведения')),
                ('description', models.CharField(max_length=255, verbose_name='Описание')),
                ('photo', models.ImageField(upload_to='', verbose_name='Фото')),
                ('result', models.CharField(max_length=255, verbose_name='Результат')),
            ],
        ),
        migrations.CreateModel(
            name='Federation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('logo', models.ImageField(upload_to='', verbose_name='Логотип')),
            ],
        ),
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Дата проведения')),
                ('score', models.CharField(max_length=20, verbose_name='Счет')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('article', models.TextField(max_length=1000, verbose_name='Текст новости')),
                ('photo', models.ImageField(upload_to='', verbose_name='Фото')),
                ('dateofadd', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
            ],
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.CharField(max_length=255, verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('surname', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('age', models.IntegerField(verbose_name='Возраст')),
                ('photo', models.ImageField(upload_to='', verbose_name='Фото')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Электронная почта')),
                ('dateofadd', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sportpro_app.sport', verbose_name='Вид спорта')),
            ],
        ),
    ]
