# Generated by Django 3.2.3 on 2021-07-11 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('date', models.DateTimeField(verbose_name='Дата проведения')),
                ('location', models.CharField(max_length=255, verbose_name='Место проведения')),
                ('description', models.CharField(max_length=255, verbose_name='Описание')),
                ('photo', models.URLField(verbose_name='Фото')),
                ('result', models.CharField(max_length=255, verbose_name='Результат')),
            ],
            options={
                'verbose_name': 'Соревнования',
                'verbose_name_plural': 'Соревнования',
            },
        ),
        migrations.CreateModel(
            name='Federation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
                ('logo', models.URLField(verbose_name='Логотип')),
                ('description', models.CharField(max_length=255, verbose_name='О нас')),
                ('contacts', models.CharField(max_length=255, verbose_name='Контакты')),
            ],
            options={
                'verbose_name': 'Федерация Спорта',
                'verbose_name_plural': 'Федерации Спорта',
            },
        ),
        migrations.CreateModel(
            name='Grid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(max_length=10, verbose_name='Stage')),
            ],
            options={
                'verbose_name': 'Grid',
                'verbose_name_plural': 'Grids',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='Number')),
                ('date', models.DateTimeField(null=True, verbose_name='Дата проведения')),
                ('player1_score', models.IntegerField(default=0, verbose_name='Счет первого спортсмена')),
                ('player2_score', models.IntegerField(default=0, verbose_name='Счет второго спортсмена')),
            ],
            options={
                'verbose_name': 'Матч',
                'verbose_name_plural': 'Матчи',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('article', models.TextField(max_length=1000, verbose_name='Текст новости')),
                ('photo', models.URLField(verbose_name='Фото')),
                ('dateofadd', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('tags', models.CharField(max_length=50, verbose_name='Тэги')),
            ],
            options={
                'verbose_name': 'Новости',
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('surname', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('age', models.IntegerField(default=18, verbose_name='Возраст')),
                ('sex', models.CharField(max_length=255, verbose_name='Пол')),
                ('weight', models.IntegerField(default=60, verbose_name='Весовая категория')),
                ('photo', models.URLField(null=True, verbose_name='Фото')),
                ('dateofadd', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
            ],
            options={
                'verbose_name': 'Спортсмен',
                'verbose_name_plural': 'Спортсмены',
            },
        ),
        migrations.CreateModel(
            name='PlayerCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Категория Спортсмена')),
            ],
            options={
                'verbose_name': 'Категория Спортсмена',
                'verbose_name_plural': 'Категории Спортсменов',
            },
        ),
        migrations.CreateModel(
            name='SportCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Категория вида спорта')),
            ],
            options={
                'verbose_name': 'Категория Спорта',
                'verbose_name_plural': 'Категории Спорта',
            },
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('description', models.CharField(max_length=255, verbose_name='Описание')),
                ('photo', models.URLField(verbose_name='Фото')),
                ('short_desc', models.CharField(max_length=100, verbose_name='Краткое описание')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sportpro_app.sportcategory', verbose_name='Категория спорта')),
            ],
            options={
                'verbose_name': 'Вид Спорта',
                'verbose_name_plural': 'Виды Спорта',
            },
        ),
        migrations.CreateModel(
            name='PlayerToEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Is approved')),
                ('final_score', models.PositiveSmallIntegerField(default=0, verbose_name='Итоговые очки')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sportpro_app.event', verbose_name='Соревнование')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sportpro_app.player', verbose_name='Спортсмен')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='playercategory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sportpro_app.playercategory', verbose_name='Категория спортсмена'),
        ),
        migrations.AddField(
            model_name='player',
            name='sport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sportpro_app.sport', verbose_name='Вид спорта'),
        ),
    ]
