# Generated by Django 3.2.3 on 2021-07-11 13:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sportpro_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Тренер'),
        ),
        migrations.AddField(
            model_name='news',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='news',
            name='sport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sportpro_app.sport', verbose_name='Вид спорта'),
        ),
        migrations.AddField(
            model_name='matches',
            name='grid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='sportpro_app.grid', verbose_name='Сетка'),
        ),
        migrations.AddField(
            model_name='matches',
            name='judge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Судья'),
        ),
        migrations.AddField(
            model_name='matches',
            name='player1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player1', to='sportpro_app.player', verbose_name='Первый Спортсмен'),
        ),
        migrations.AddField(
            model_name='matches',
            name='player2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player2', to='sportpro_app.player', verbose_name='Второй Спортсмен'),
        ),
        migrations.AddField(
            model_name='matches',
            name='winner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='winner', to='sportpro_app.player', verbose_name='Победитель'),
        ),
        migrations.AddField(
            model_name='grid',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grids', to='sportpro_app.event', verbose_name='Event'),
        ),
        migrations.AddField(
            model_name='federation',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Админ Федерации'),
        ),
        migrations.AddField(
            model_name='federation',
            name='sport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sportpro_app.sport', verbose_name='Вид спорта'),
        ),
        migrations.AddField(
            model_name='event',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Организатор'),
        ),
        migrations.AddField(
            model_name='event',
            name='players',
            field=models.ManyToManyField(through='sportpro_app.PlayerToEvent', to='sportpro_app.Player', verbose_name='Спортсмены'),
        ),
        migrations.AddField(
            model_name='event',
            name='sport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sportpro_app.sport', verbose_name='Вид спорта'),
        ),
    ]
