# Generated by Django 3.2.3 on 2021-05-26 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sportpro_app', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.trainer', verbose_name='Тренер'),
        ),
        migrations.AddField(
            model_name='news',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.editor', verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='matches',
            name='player1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player1', to='sportpro_app.player', verbose_name='Первый Спортсмен'),
        ),
        migrations.AddField(
            model_name='matches',
            name='player2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player2', to='sportpro_app.player', verbose_name='Второй Спортсмен'),
        ),
        migrations.AddField(
            model_name='matches',
            name='winner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winner', to='sportpro_app.player', verbose_name='Победитель'),
        ),
        migrations.AddField(
            model_name='federation',
            name='Admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.admin', verbose_name='Админ Федерации'),
        ),
        migrations.AddField(
            model_name='federation',
            name='sport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sportpro_app.sport', verbose_name='Вид спорта'),
        ),
        migrations.AddField(
            model_name='event',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.admin', verbose_name='Организатор'),
        ),
        migrations.AddField(
            model_name='event',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sportpro_app.player', verbose_name='Спортсмены'),
        ),
        migrations.AddField(
            model_name='event',
            name='sport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sportpro_app.sport', verbose_name='Вид спорта'),
        ),
    ]
