# Generated by Django 3.2.3 on 2021-05-29 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sportpro_app', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='federation',
            name='contacts',
            field=models.CharField(default='', max_length=255, verbose_name='Контакты'),
        ),
        migrations.AddField(
            model_name='federation',
            name='description',
            field=models.CharField(default='', max_length=255, verbose_name='О нас'),
        ),
        migrations.AddField(
            model_name='news',
            name='sport',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='sportpro_app.sport', verbose_name='Вид спорта'),
        ),
    ]
