# Generated by Django 3.2.3 on 2021-05-31 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sportpro_app', '0003_auto_20210529_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='federation',
            name='contacts',
            field=models.CharField(max_length=255, verbose_name='Контакты'),
        ),
        migrations.AlterField(
            model_name='federation',
            name='description',
            field=models.CharField(max_length=255, verbose_name='О нас'),
        ),
        migrations.AlterField(
            model_name='news',
            name='sport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sportpro_app.sport', verbose_name='Вид спорта'),
        ),
    ]
