# Generated by Django 3.2.3 on 2021-06-02 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sportpro_app', '0004_auto_20210531_1901'),
    ]

    operations = [
        migrations.CreateModel(
            name='SportCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Категория вида спорта')),
            ],
        ),
        migrations.AddField(
            model_name='sport',
            name='category',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='sportpro_app.sportcategory', verbose_name='Категория спорта'),
        ),
    ]
