# Generated by Django 3.2.3 on 2021-07-19 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sportpro_app', '0004_alter_matches_judge'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoForGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.URLField(verbose_name='Фотография')),
                ('dateofadd', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
            ],
        ),
        migrations.AlterModelOptions(
            name='grid',
            options={'ordering': ['-id'], 'verbose_name': 'Сетка', 'verbose_name_plural': 'Сетки'},
        ),
        migrations.AlterModelOptions(
            name='playertoevent',
            options={'verbose_name': 'Спортсмен на соревнования', 'verbose_name_plural': 'Спортсмены на соревнования'},
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags', models.CharField(max_length=100, verbose_name='Тэги')),
                ('federation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sportpro_app.federation', verbose_name='Федерация')),
                ('photo', models.ManyToManyField(to='sportpro_app.PhotoForGallery', verbose_name='Фотографии')),
            ],
        ),
    ]
