# Generated by Django 3.2.3 on 2021-07-21 14:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sportpro_app', '0005_auto_20210719_2323'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name': 'Галерея', 'verbose_name_plural': 'Галереи'},
        ),
        migrations.AlterModelOptions(
            name='photoforgallery',
            options={'verbose_name': 'Фото для Галереи', 'verbose_name_plural': 'Фото для Галереи'},
        ),
        migrations.AddField(
            model_name='federation',
            name='address',
            field=models.CharField(default='228', max_length=255, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='federation',
            name='judge',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sportpro_app.Federation.judge+', to=settings.AUTH_USER_MODEL, verbose_name='Представитель Судейской Коллегии'),
        ),
    ]
