# Generated by Django 3.2.3 on 2021-06-02 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sportpro_app', '0005_auto_20210602_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sport',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sportpro_app.sportcategory', verbose_name='Категория спорта'),
        ),
    ]
