# Generated by Django 3.2.3 on 2021-06-03 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sportpro_app', '0006_alter_sport_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='federation',
            old_name='Admin',
            new_name='admin',
        ),
    ]
