# Generated by Django 3.2.3 on 2021-07-21 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportpro_app', '0006_auto_20210721_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(default='Регистрация открыта', max_length=255, verbose_name='Статус'),
        ),
    ]
