# Generated by Django 3.2.3 on 2021-07-28 09:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportpro_app', '0007_event_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='date',
        ),
        migrations.AddField(
            model_name='event',
            name='dateofend',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата окончания'),
        ),
        migrations.AddField(
            model_name='event',
            name='dateofstart',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата начала'),
        ),
        migrations.AddField(
            model_name='event',
            name='protocol',
            field=models.URLField(null=True, verbose_name='Протокол'),
        ),
        migrations.AddField(
            model_name='event',
            name='startofWeighing',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
