# Generated by Django 3.2.3 on 2021-06-03 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_judge'),
        ('sportpro_app', '0007_rename_admin_federation_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='matches',
            name='judge',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='user.judge', verbose_name='Судья'),
        ),
    ]
