# Generated by Django 3.2.3 on 2021-07-28 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportpro_app', '0008_auto_20210728_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='middlename',
            field=models.CharField(default=' ', max_length=255, verbose_name='Отчество'),
        ),
    ]
