# Generated by Django 3.2.3 on 2021-06-03 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sportpro_app', '0009_alter_matches_judge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matches',
            name='judge',
        ),
    ]
