# Generated by Django 3.2.3 on 2021-06-20 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sportpro_app', '0010_remove_matches_judge'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Категория Спортсмена')),
            ],
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Соревнования', 'verbose_name_plural': 'Соревнования'},
        ),
        migrations.AlterModelOptions(
            name='federation',
            options={'verbose_name': 'Федерация Спорта', 'verbose_name_plural': 'Федерации Спорта'},
        ),
        migrations.AlterModelOptions(
            name='matches',
            options={'verbose_name': 'Матч', 'verbose_name_plural': 'Матчи'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'Новости', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AlterModelOptions(
            name='player',
            options={'verbose_name': 'Спортсмен', 'verbose_name_plural': 'Спортсмены'},
        ),
        migrations.AlterModelOptions(
            name='sport',
            options={'verbose_name': 'Вид Спорта', 'verbose_name_plural': 'Виды Спорта'},
        ),
        migrations.AlterModelOptions(
            name='sportcategory',
            options={'verbose_name': 'Категория Спорта', 'verbose_name_plural': 'Категории Спорта'},
        ),
        migrations.RemoveField(
            model_name='matches',
            name='score',
        ),
        migrations.RemoveField(
            model_name='player',
            name='email',
        ),
        migrations.AddField(
            model_name='matches',
            name='player1_score',
            field=models.IntegerField(default=0, verbose_name='Счет первого спортсмена'),
        ),
        migrations.AddField(
            model_name='matches',
            name='player2_score',
            field=models.IntegerField(default=0, verbose_name='Счет второго спортсмена'),
        ),
        migrations.AddField(
            model_name='player',
            name='sex',
            field=models.CharField(default='Мужчина', max_length=255, unique=True, verbose_name='Пол'),
        ),
        migrations.AddField(
            model_name='player',
            name='weight',
            field=models.IntegerField(default=60, verbose_name='Весовая категория'),
        ),
        migrations.AlterField(
            model_name='event',
            name='photo',
            field=models.URLField(verbose_name='Фото'),
        ),
        migrations.RemoveField(
            model_name='event',
            name='player',
        ),
        migrations.AddField(
            model_name='event',
            name='player',
            field=models.ManyToManyField(to='sportpro_app.Player', verbose_name='Спортсмены'),
        ),
        migrations.AlterField(
            model_name='federation',
            name='logo',
            field=models.URLField(verbose_name='Логотип'),
        ),
        migrations.AlterField(
            model_name='federation',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='news',
            name='photo',
            field=models.URLField(verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='player',
            name='age',
            field=models.IntegerField(default=18, verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='player',
            name='photo',
            field=models.URLField(verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='player',
            name='surname',
            field=models.CharField(max_length=255, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='sport',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='sportcategory',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Категория вида спорта'),
        ),
        migrations.AddField(
            model_name='player',
            name='playercategory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sportpro_app.playercategory', verbose_name='Категория спортсмена'),
        ),
    ]
