# Generated by Django 3.2.3 on 2021-07-28 18:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportpro_app', '0010_player_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='age',
        ),
        migrations.AddField(
            model_name='player',
            name='dateofbirth',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Дата рождения'),
        ),
    ]
