# Generated by Django 3.2.3 on 2021-06-30 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportpro_app', '0012_alter_news_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playercategory',
            options={'verbose_name': 'Категория Спортсмена', 'verbose_name_plural': 'Категории Спортсменов'},
        ),
        migrations.AlterField(
            model_name='player',
            name='sex',
            field=models.CharField(default='Мужчина', max_length=255, verbose_name='Пол'),
        ),
    ]
