# Generated by Django 3.2.3 on 2021-06-30 08:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sportpro_app', '0016_alter_player_trainer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='trainer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Тренер'),
        ),
    ]
