# Generated by Django 3.2.3 on 2021-06-30 09:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sportpro_app', '0017_alter_player_trainer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matches',
            name='judge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Судья'),
        ),
        migrations.AlterField(
            model_name='player',
            name='sex',
            field=models.CharField(max_length=255, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='player',
            name='trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Тренер'),
        ),
    ]
