# Generated by Django 3.2.3 on 2021-07-07 14:24

from django.db import migrations, models
from django.db.migrations.operations.fields import RemoveField
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sportpro_app', '0018_auto_20210630_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='matches',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='sportpro_app.event', verbose_name='Соревнование'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='PlayerToEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sportpro_app.event', verbose_name='Соревнование')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sportpro_app.player', verbose_name='Спортсмен')),
            ],
        ),
        migrations.RemoveField(
            model_name='event',
            name='player'
        ),
        migrations.AddField(
            model_name='event',
            name='player',
            field=models.ManyToManyField(through='sportpro_app.PlayerToEvent', to='sportpro_app.Player', verbose_name='Спортсмены'),
        ),
    ]
