# Generated by Django 3.2.3 on 2021-07-07 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sportpro_app', '0019_auto_20210707_2024'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='player',
            new_name='players',
        ),
    ]
