# Generated by Django 3.2.3 on 2021-07-07 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportpro_app', '0020_rename_player_event_players'),
    ]

    operations = [
        migrations.AddField(
            model_name='playertoevent',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Is approved'),
        ),
    ]
