# Generated by Django 3.2.3 on 2021-07-08 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sportpro_app', '0022_alter_player_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matches',
            name='event',
        ),
        migrations.CreateModel(
            name='Grid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(max_length=10, verbose_name='Stage')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sportpro_app.event', verbose_name='Event')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sportpro_app.matches', verbose_name='Match')),
            ],
            options={
                'verbose_name': 'Grid',
                'verbose_name_plural': 'Grids',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='event',
            name='matches',
            field=models.ManyToManyField(through='sportpro_app.Grid', to='sportpro_app.Matches', verbose_name='Matches'),
        ),
    ]
