# Generated by Django 3.2.3 on 2021-07-08 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sportpro_app', '0023_auto_20210708_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matches',
            name='date',
            field=models.DateTimeField(null=True, verbose_name='Дата проведения'),
        ),
        migrations.AlterField(
            model_name='matches',
            name='winner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='winner', to='sportpro_app.player', verbose_name='Победитель'),
        ),
    ]
