# Generated by Django 3.2.3 on 2021-07-08 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportpro_app', '0024_auto_20210708_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='grid',
            name='number',
            field=models.PositiveIntegerField(default=0, verbose_name='Number'),
            preserve_default=False,
        ),
    ]
