# Generated by Django 3.2.3 on 2021-07-09 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportpro_app', '0026_auto_20210709_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='playertoevent',
            name='final_score',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Итоговые очки'),
        ),
    ]
