# Generated by Django 3.2.3 on 2021-07-11 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='document',
            field=models.URLField(null=True, verbose_name='Документ'),
        ),
        migrations.AddField(
            model_name='user',
            name='organization',
            field=models.CharField(default='Глаз тигра', max_length=255, verbose_name='Организация'),
        ),
    ]
