# Generated by Django 3.2.3 on 2021-07-11 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210711_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='document',
            field=models.URLField(blank=True, null=True, verbose_name='Документ'),
        ),
        migrations.AlterField(
            model_name='user',
            name='organization',
            field=models.CharField(blank=True, default='Глаз тигра', max_length=255, verbose_name='Организация'),
        ),
    ]
