# Generated by Django 3.2.3 on 2021-06-03 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_user_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='FederationID',
        ),
    ]
