# Generated by Django 3.2.3 on 2021-06-03 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_judge'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Judge',
        ),
    ]
