# Generated by Django 3.2.3 on 2021-07-08 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
